# Generated by Django 6.0.4 on 2026-04-27 04:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ / CPF')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PR', max_length=2, verbose_name='UF')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(blank=True, choices=[('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('transporte', 'Transporte (ônibus/taxi/uber)'), ('estacionamento', 'Estacionamento'), ('material', 'Material / Ferramentas'), ('comunicacao', 'Comunicação / Telefone'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de despesa')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('limite_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo por ocorrência. Deixe em branco para sem limite.', max_digits=10, null=True, verbose_name='Limite de valor (R$)')),
                ('valor_km', models.DecimalField(blank=True, decimal_places=4, help_text='Preencha apenas para política de quilometragem.', max_digits=6, null=True, verbose_name='Valor por km (R$)')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Política de Valor',
                'verbose_name_plural': 'Políticas de Valores',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('faturado', 'Faturado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('cidade_atendimento', models.CharField(max_length=100, verbose_name='Cidade de atendimento')),
                ('uf_atendimento', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='PR', max_length=2, verbose_name='UF')),
                ('tipo_localidade', models.CharField(choices=[('capital', 'Capital'), ('interior', 'Interior')], default='interior', max_length=10, verbose_name='Tipo de localidade')),
                ('data_inicio', models.DateField(verbose_name='Data início do atendimento')),
                ('data_fim', models.DateField(verbose_name='Data fim do atendimento')),
                ('motivo', models.TextField(verbose_name='Motivo / Descrição do serviço')),
                ('area_gasto', models.CharField(blank=True, help_text='Ex: Manutenção, Instalação, Comercial...', max_length=100, verbose_name='Área / Centro de custo')),
                ('valor_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Adiantamento recebido (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='relatorios.cliente', verbose_name='Cliente')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_responsavel', to='relatorios.tecnico', verbose_name='Técnico responsável')),
            ],
            options={
                'verbose_name': 'Relatório Técnico',
                'verbose_name_plural': 'Relatórios Técnicos',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('transporte', 'Transporte (ônibus/taxi/uber)'), ('estacionamento', 'Estacionamento'), ('material', 'Material / Ferramentas'), ('comunicacao', 'Comunicação / Telefone'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição / Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (R$)')),
                ('quem_pagou', models.CharField(choices=[('tecnico', 'Técnico (reembolsável)'), ('empresa', 'Empresa (cartão/direto)')], default='tecnico', max_length=10, verbose_name='Quem pagou')),
                ('reembolsavel', models.BooleanField(default=True, help_text='Despesas pagas pela empresa não são reembolsáveis.', verbose_name='Reembolsável')),
                ('centro_custo', models.CharField(blank=True, max_length=100, verbose_name='Centro de custo / Classificação')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='relatorios.relatoriotecnico', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Item de Despesa',
                'verbose_name_plural': 'Itens de Despesa',
                'ordering': ['ordem', 'data', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioTecnicoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('responsavel', 'Responsável'), ('apoio', 'Apoio')], default='apoio', max_length=15, verbose_name='Papel')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='relatorios.relatoriotecnico', verbose_name='Relatório')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relatorios.tecnico', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Técnico da Equipe',
                'verbose_name_plural': 'Técnicos da Equipe',
                'unique_together': {('relatorio', 'tecnico')},
            },
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='tecnicos_adicionais',
            field=models.ManyToManyField(blank=True, related_name='relatorios_equipe', through='relatorios.RelatorioTecnicoEquipe', to='relatorios.tecnico', verbose_name='Equipe adicional'),
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adiantamento', 'Adiantamento'), ('reembolso', 'Reembolso')], default='adiantamento', max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (R$)')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adiantamentos', to='relatorios.relatoriotecnico', verbose_name='Relatório vinculado')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='relatorios.tecnico', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Adiantamento',
                'verbose_name_plural': 'Adiantamentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TrechoKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('data', models.DateField(verbose_name='Data')),
                ('origem', models.CharField(max_length=150, verbose_name='Origem')),
                ('destino', models.CharField(max_length=150, verbose_name='Destino')),
                ('km', models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Quilômetros')),
                ('valor_km', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Preenchido automaticamente pela política vigente.', max_digits=6, verbose_name='Valor por km (R$)')),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Valor calculado (R$)')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='relatorios.relatoriotecnico', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Trecho de KM',
                'verbose_name_plural': 'Trechos de KM',
                'ordering': ['ordem', 'data'],
            },
        ),
    ]
