# Generated by Django 6.0.4 on 2026-04-27 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdespesa',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='itemdespesa',
            name='reembolsavel',
        ),
        migrations.RemoveField(
            model_name='relatoriotecnico',
            name='area_gasto',
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='centro_custo',
            field=models.CharField(blank=True, help_text='Aplicado a todos os itens deste relatório.', max_length=100, verbose_name='Centro de custo / Classificação'),
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='relatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adiantamentos', to='relatorios.relatoriotecnico'),
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='relatorios.tecnico'),
        ),
        migrations.AlterField(
            model_name='itemdespesa',
            name='quem_pagou',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('empresa', 'Empresa')], default='tecnico', max_length=10, verbose_name='Quem pagou'),
        ),
        migrations.AlterField(
            model_name='itemdespesa',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='relatorios.relatoriotecnico'),
        ),
        migrations.AlterField(
            model_name='itemdespesa',
            name='tipo',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('transporte', 'Transporte'), ('estacionamento', 'Estacionamento'), ('material', 'Material / Ferramentas'), ('comunicacao', 'Comunicação / Telefone'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='politicavalor',
            name='limite_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite de valor (R$)'),
        ),
        migrations.AlterField(
            model_name='politicavalor',
            name='tipo_despesa',
            field=models.CharField(blank=True, choices=[('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('transporte', 'Transporte'), ('estacionamento', 'Estacionamento'), ('material', 'Material / Ferramentas'), ('comunicacao', 'Comunicação / Telefone'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de despesa'),
        ),
        migrations.AlterField(
            model_name='politicavalor',
            name='valor_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Valor por km (R$)'),
        ),
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='data_fim',
            field=models.DateField(verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='data_inicio',
            field=models.DateField(verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='relatoriotecnicoequipe',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='relatorios.relatoriotecnico'),
        ),
        migrations.AlterField(
            model_name='relatoriotecnicoequipe',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relatorios.tecnico'),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='relatorios.relatoriotecnico'),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='valor_km',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=6, verbose_name='Valor por km (R$)'),
        ),
    ]
