# Generated by Django 6.0.4 on 2026-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_v3_single_save_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado')], default='rascunho', max_length=20),
        ),
    ]
