# Generated by Django 6.0.4 on 2026-05-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0009_normaliza_valores_aprovados_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdespesa',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
