# Generated by Django 6.0.4 on 2026-05-15 12:34

from django.db import migrations, models


def migrar_status_antigos(apps, schema_editor):
    RelatorioTecnico = apps.get_model("relatorios", "RelatorioTecnico")
    RelatorioTecnico.objects.filter(status="pendente").update(
        status="conferencia_pendente"
    )
    RelatorioTecnico.objects.filter(status__in=["faturado", "fechado"]).update(
        status="aprovado"
    )


def reverter_status_antigos(apps, schema_editor):
    RelatorioTecnico = apps.get_model("relatorios", "RelatorioTecnico")
    RelatorioTecnico.objects.filter(status="conferencia_pendente").update(
        status="pendente"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0010_alter_itemdespesa_data_alter_trechokm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('conferencia_pendente', 'Conferência pendente'), ('ajuste_pendente', 'Ajuste pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=30, verbose_name='Status'),
        ),
        migrations.RunPython(migrar_status_antigos, reverter_status_antigos),
    ]
