# Generated by Django 6.0.4 on 2026-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0011_alter_relatoriotecnico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnico',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Justificativa financeira'),
        ),
    ]
