# Generated by Django 6.0.4 on 2026-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0013_historicorelatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdespesa',
            name='motivo_recusa',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='status_financeiro',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=10, verbose_name='Status financeiro'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='motivo_recusa',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='status_financeiro',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=10, verbose_name='Status financeiro'),
        ),
    ]
