# Generated by Django 6.0.4 on 2026-05-15 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_rejeicoes_financeiras(apps, schema_editor):
    ItemDespesa = apps.get_model("relatorios", "ItemDespesa")
    TrechoKm = apps.get_model("relatorios", "TrechoKm")

    for modelo in (ItemDespesa, TrechoKm):
        for item in modelo.objects.filter(status_financeiro="rejeitado"):
            item.rejeitado = True
            item.motivo_rejeicao = item.motivo_recusa or ""
            item.save(update_fields=["rejeitado", "motivo_rejeicao"])


def reverter_rejeicoes_financeiras(apps, schema_editor):
    ItemDespesa = apps.get_model("relatorios", "ItemDespesa")
    TrechoKm = apps.get_model("relatorios", "TrechoKm")

    for modelo in (ItemDespesa, TrechoKm):
        modelo.objects.filter(rejeitado=True).update(
            status_financeiro="rejeitado",
            motivo_recusa=models.F("motivo_rejeicao"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0014_itemdespesa_motivo_recusa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdespesa',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='rejeitado',
            field=models.BooleanField(default=False, verbose_name='Rejeitado pelo financeiro'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='rejeitado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejeitado em'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='rejeitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_rejeitadas', to=settings.AUTH_USER_MODEL, verbose_name='Rejeitado por'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='rejeitado',
            field=models.BooleanField(default=False, verbose_name='Rejeitado pelo financeiro'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='rejeitado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejeitado em'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='rejeitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_km_rejeitados', to=settings.AUTH_USER_MODEL, verbose_name='Rejeitado por'),
        ),
        migrations.RunPython(
            migrar_rejeicoes_financeiras,
            reverter_rejeicoes_financeiras,
        ),
    ]
