# Generated by Django 6.0.4 on 2026-05-19 20:01

import django.db.models.deletion
from django.db import migrations, models


def popular_clientes_legados(apps, schema_editor):
    RelatorioTecnico = apps.get_model('relatorios', 'RelatorioTecnico')
    RelatorioCliente = apps.get_model('relatorios', 'RelatorioCliente')
    DespesaCliente = apps.get_model('relatorios', 'DespesaCliente')
    TrechoKMCliente = apps.get_model('relatorios', 'TrechoKMCliente')

    for relatorio in RelatorioTecnico.objects.exclude(cliente_id__isnull=True):
        RelatorioCliente.objects.get_or_create(
            relatorio_id=relatorio.pk,
            cliente_id=relatorio.cliente_id,
            defaults={'ordem': 0},
        )
        for despesa in relatorio.despesas.all():
            DespesaCliente.objects.get_or_create(
                despesa_id=despesa.pk,
                cliente_id=relatorio.cliente_id,
            )
        for trecho in relatorio.trechos.all():
            TrechoKMCliente.objects.get_or_create(
                trecho_id=trecho.pk,
                cliente_id=relatorio.cliente_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0019_relatoriotecnico_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_cliente', to='relatorios.cliente')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to='relatorios.itemdespesa')),
            ],
            options={
                'verbose_name': 'Cliente da Despesa',
                'verbose_name_plural': 'Clientes da Despesa',
                'unique_together': {('despesa', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='RelatorioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_cliente', to='relatorios.cliente')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to='relatorios.relatoriotecnico')),
            ],
            options={
                'verbose_name': 'Cliente do Relatorio',
                'verbose_name_plural': 'Clientes do Relatorio',
                'ordering': ['ordem', 'cliente__nome'],
                'unique_together': {('relatorio', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='TrechoKMCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trechos_km_cliente', to='relatorios.cliente')),
                ('trecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to='relatorios.trechokm')),
            ],
            options={
                'verbose_name': 'Cliente do Trecho KM',
                'verbose_name_plural': 'Clientes dos Trechos KM',
                'unique_together': {('trecho', 'cliente')},
            },
        ),
        migrations.RunPython(popular_clientes_legados, migrations.RunPython.noop),
    ]
