# Generated by Django 6.0.4 on 2026-05-20 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0020_despesacliente_relatoriocliente_trechokmcliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('auto', 'Automático'), ('adjusted', 'Ajustado'), ('approved', 'Aprovado')], default='auto', max_length=10)),
                ('motivo_ajuste', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_despesa_alterados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_despesas', to='relatorios.cliente')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='relatorios.itemdespesa')),
            ],
            options={
                'verbose_name': 'Rateio da Despesa',
                'verbose_name_plural': 'Rateios das Despesas',
                'ordering': ['cliente__nome'],
                'unique_together': {('despesa', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='TrechoRateioKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_original', models.DecimalField(decimal_places=1, max_digits=8)),
                ('km_final', models.DecimalField(decimal_places=1, max_digits=8)),
                ('valor_rateado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('auto', 'Automático'), ('adjusted', 'Ajustado'), ('approved', 'Aprovado')], default='auto', max_length=10)),
                ('motivo_ajuste', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_km_alterados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_trechos_km', to='relatorios.cliente')),
                ('trecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='relatorios.trechokm')),
            ],
            options={
                'verbose_name': 'Rateio do Trecho KM',
                'verbose_name_plural': 'Rateios dos Trechos KM',
                'ordering': ['cliente__nome'],
                'unique_together': {('trecho', 'cliente')},
            },
        ),
    ]
