# Generated by Django 6.0.4 on 2026-05-20 16:09

from decimal import Decimal
from django.db import migrations, models


def migrar_valores_km_legados(apps, schema_editor):
    TrechoRateioKM = apps.get_model("relatorios", "TrechoRateioKM")
    for rateio in TrechoRateioKM.objects.all().iterator():
        rateio.km_cliente = rateio.km_final or Decimal("0.0")
        rateio.valor_calculado = rateio.valor_rateado or Decimal("0.00")
        rateio.valor_final = rateio.valor_rateado or Decimal("0.00")
        if rateio.km_cliente:
            rateio.valor_km = (rateio.valor_calculado / rateio.km_cliente).quantize(
                Decimal("0.0001")
            )
        rateio.save(
            update_fields=[
                "km_cliente",
                "valor_calculado",
                "valor_final",
                "valor_km",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0021_despesarateio_trechorateiokm'),
    ]

    operations = [
        migrations.AddField(
            model_name='trechorateiokm',
            name='km_cliente',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='trechorateiokm',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='trechorateiokm',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='trechorateiokm',
            name='valor_km',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.RunPython(migrar_valores_km_legados, migrations.RunPython.noop),
    ]
