# Generated by Django 6.0.4 on 2026-05-21 13:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0022_trechorateiokm_km_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnico',
            name='tipo_relatorio',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('operacional', 'Operacional')], default='operacional', max_length=20, verbose_name='Tipo de relatorio'),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quilômetros'),
        ),
        migrations.AlterField(
            model_name='trechorateiokm',
            name='km_cliente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='trechorateiokm',
            name='km_final',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trechorateiokm',
            name='km_original',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
