# Generated by Django 6.0.4 on 2026-05-21 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0023_relatoriotecnico_tipo_relatorio_alter_trechokm_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioSnapshotFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('conferencia_pendente', 'Conferência pendente'), ('ajuste_pendente', 'Ajuste pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], max_length=30)),
                ('total_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_aprovado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferenca_removida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('finalizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_financeiros_finalizados', to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_financeiro', to='relatorios.relatoriotecnico')),
            ],
            options={
                'verbose_name': 'Snapshot financeiro do relatorio',
                'verbose_name_plural': 'Snapshots financeiros dos relatorios',
                'ordering': ['-finalizado_em'],
            },
        ),
    ]
