# Generated by Django 6.0.4 on 2026-05-21 15:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0024_relatoriosnapshotfinanceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='valor_adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Adiantamento recebido (R$)'),
        ),
    ]
