# Generated by Django 6.0.4 on 2026-05-22 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0028_repair_trechokm_geocoding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trechokm',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_km/%Y/%m/', verbose_name='Comprovante'),
        ),
        migrations.CreateModel(
            name='AnexoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_relatorios/%Y/%m/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original')),
                ('tipo_mime', models.CharField(blank=True, max_length=120, verbose_name='Tipo MIME')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='relatorios.itemdespesa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_relatorios_enviados', to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='relatorios.relatoriotecnico')),
                ('trecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='relatorios.trechokm')),
            ],
            options={
                'verbose_name': 'Anexo do Relatorio',
                'verbose_name_plural': 'Anexos dos Relatorios',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['relatorio', 'criado_em'], name='relatorios__relator_52af4a_idx'), models.Index(fields=['despesa'], name='relatorios__despesa_2ca806_idx'), models.Index(fields=['trecho'], name='relatorios__trecho__39a055_idx')],
            },
        ),
    ]
