# Generated by Django 6.0.4 on 2026-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0029_trechokm_comprovante_anexorelatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexorelatorio',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nº do documento'),
        ),
        migrations.AddField(
            model_name='anexorelatorio',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('nota_fiscal', 'Nota Fiscal'), ('recibo', 'Recibo')], max_length=20, verbose_name='Tipo do documento'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='numero_documento_comprovante',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nº do documento'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='tipo_documento_comprovante',
            field=models.CharField(blank=True, choices=[('nota_fiscal', 'Nota Fiscal'), ('recibo', 'Recibo')], max_length=20, verbose_name='Tipo do documento'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='numero_documento_comprovante',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nº do documento'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='tipo_documento_comprovante',
            field=models.CharField(blank=True, choices=[('nota_fiscal', 'Nota Fiscal'), ('recibo', 'Recibo')], max_length=20, verbose_name='Tipo do documento'),
        ),
    ]

