# Generated by Django 6.0.4 on 2026-05-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0028_repair_trechokm_geocoding_fields'),
        ('relatorios', '0030_documento_comprovante_tipo_numero'),
    ]

    operations = [
    ]
