# Generated by Django 6.0.4 on 2026-05-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0031_merge_20260522_1324'),
        ('relatorios', '0032_perfilusuario'),
    ]

    operations = [
    ]
