# Generated by Django 6.0.4 on 2026-05-22 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0032_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemdespesa',
            index=models.Index(fields=['relatorio', 'data'], name='relatorios__relator_be258b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdespesa',
            index=models.Index(fields=['relatorio', 'tipo'], name='relatorios__relator_29f6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdespesa',
            index=models.Index(fields=['status_financeiro', 'rejeitado'], name='relatorios__status__dce172_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriosnapshotfinanceiro',
            index=models.Index(fields=['status', 'finalizado_em'], name='relatorios__status_7d6c82_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriotecnico',
            index=models.Index(fields=['status', 'data_inicio'], name='relatorios__status_752c99_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriotecnico',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='relatorios__data_in_3ae1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriotecnico',
            index=models.Index(fields=['criado_em'], name='relatorios__criado__9d4e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='trechokm',
            index=models.Index(fields=['relatorio', 'data'], name='relatorios__relator_3a7926_idx'),
        ),
        migrations.AddIndex(
            model_name='trechokm',
            index=models.Index(fields=['status_financeiro', 'rejeitado'], name='relatorios__status__bca267_idx'),
        ),
        migrations.AddIndex(
            model_name='trechokm',
            index=models.Index(fields=['diferenca_km_percentual'], name='relatorios__diferen_bcb9fd_idx'),
        ),
    ]
