# Generated by Django 6.0.4 on 2026-05-25 17:13

from django.db import migrations, models


def copiar_motivo_legado(apps, schema_editor):
    RelatorioCliente = apps.get_model("relatorios", "RelatorioCliente")
    for vinculo in RelatorioCliente.objects.select_related("relatorio").iterator():
        motivo = (getattr(vinculo.relatorio, "motivo", "") or "").strip()
        if motivo and not (vinculo.motivo_viagem or "").strip():
            vinculo.motivo_viagem = motivo
            vinculo.save(update_fields=["motivo_viagem"])


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0033_itemdespesa_relatorios__relator_be258b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriocliente',
            name='motivo_viagem',
            field=models.TextField(blank=True, verbose_name='Motivo da viagem'),
        ),
        migrations.RunPython(copiar_motivo_legado, migrations.RunPython.noop),
    ]
