# Generated by Django 6.0.4 on 2026-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0033_itemdespesa_relatorios__relator_be258b_idx_and_more'),
        ('relatorios', '0033_merge_0031_merge_20260522_1324_0032_perfilusuario'),
    ]

    operations = [
    ]
