# Generated by Django 6.0.4 on 2026-05-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0034_merge_20260522_1744'),
        ('relatorios', '0034_relatoriocliente_motivo_viagem'),
    ]

    operations = [
    ]
