# Generated by Django 6.0.4 on 2026-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0034_relatoriocliente_motivo_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicavalor',
            name='tipo_localidade',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('interior', 'Interior'), ('fronteira', 'Fronteira')], max_length=12, verbose_name='Tipo de localidade'),
        ),
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='tipo_localidade',
            field=models.CharField(choices=[('capital', 'Capital'), ('interior', 'Interior'), ('fronteira', 'Fronteira')], default='interior', max_length=10, verbose_name='Tipo de localidade'),
        ),
    ]
