# Generated by Django 6.0.4 on 2026-05-26 18:49

from datetime import date
from decimal import Decimal

from django.db import migrations, models


POLITICAS_OFICIAIS = [
    ("VALOR_KM_CONTROLSUL", "valor_km", "", "", "", "", "", None, Decimal("1.3500"), "Valor KM ControlSul"),
    ("REFEICAO_CAPITAL", "refeicao", "alimentacao", "capital", "", "", "", Decimal("80.00"), None, "Refeicao Capital"),
    ("REFEICAO_INTERIOR", "refeicao", "alimentacao", "interior", "", "", "", Decimal("60.00"), None, "Refeicao Interior"),
    ("PASSAGEM_CASCAVEL_CAMPO_GRANDE", "passagem", "transporte", "", "", "Cascavel", "Campo Grande", Decimal("1500.00"), None, "Media passagem Cascavel x Campo Grande"),
    ("PASSAGEM_CASCAVEL_SAO_PAULO", "passagem", "transporte", "", "", "Cascavel", "Sao Paulo", Decimal("1200.00"), None, "Media passagem Cascavel x Sao Paulo"),
    ("PASSAGEM_CURITIBA_CAMPO_GRANDE", "passagem", "transporte", "", "", "Curitiba", "Campo Grande", Decimal("1300.00"), None, "Media passagem Curitiba x Campo Grande"),
    ("PASSAGEM_CURITIBA_SAO_PAULO", "passagem", "transporte", "", "", "Curitiba", "Sao Paulo", Decimal("1200.00"), None, "Media passagem Curitiba x Sao Paulo"),
    ("PASSAGEM_CURITIBA_MARINGA", "passagem", "transporte", "", "", "Curitiba", "Maringa", Decimal("800.00"), None, "Media passagem Curitiba x Maringa"),
    ("PASSAGEM_CURITIBA_CASCAVEL", "passagem", "transporte", "", "", "Curitiba", "Cascavel", Decimal("1000.00"), None, "Media passagem Curitiba x Cascavel"),
    ("HOSPEDAGEM_CASCAVEL", "hospedagem", "hospedagem", "", "Cascavel", "", "", Decimal("300.00"), None, "Hospedagem Cascavel"),
    ("HOSPEDAGEM_PATO_BRANCO", "hospedagem", "hospedagem", "", "Pato Branco", "", "", Decimal("300.00"), None, "Hospedagem Pato Branco"),
    ("HOSPEDAGEM_MARINGA_LONDRINA", "hospedagem", "hospedagem", "", "Maringa/Londrina", "", "", Decimal("350.00"), None, "Hospedagem Maringa/Londrina"),
    ("HOSPEDAGEM_CURITIBA", "hospedagem", "hospedagem", "", "Curitiba", "", "", Decimal("400.00"), None, "Hospedagem Curitiba"),
    ("HOSPEDAGEM_PONTA_GROSSA", "hospedagem", "hospedagem", "", "Ponta Grossa", "", "", Decimal("350.00"), None, "Hospedagem Ponta Grossa"),
    ("HOSPEDAGEM_IRATI", "hospedagem", "hospedagem", "", "Irati", "", "", Decimal("350.00"), None, "Hospedagem Irati"),
    ("HOSPEDAGEM_SAO_PAULO", "hospedagem", "hospedagem", "", "Sao Paulo", "", "", Decimal("450.00"), None, "Hospedagem Sao Paulo"),
    ("HOSPEDAGEM_ITAJAI", "hospedagem", "hospedagem", "", "Itajai", "", "", Decimal("350.00"), None, "Hospedagem Itajai"),
    ("HOSPEDAGEM_CAMPO_GRANDE", "hospedagem", "hospedagem", "", "Campo Grande", "", "", Decimal("400.00"), None, "Hospedagem Campo Grande"),
    ("KM_DIARIO_CASCAVEL", "km_diario", "transporte", "", "Cascavel", "", "", Decimal("60.00"), None, "Media KM diario Cascavel"),
    ("KM_DIARIO_CURITIBA", "km_diario", "transporte", "", "Curitiba", "", "", Decimal("80.00"), None, "Media KM diario Curitiba"),
    ("KM_DIARIO_SAO_PAULO", "km_diario", "transporte", "", "Sao Paulo", "", "", Decimal("100.00"), None, "Media KM diario Sao Paulo"),
    ("KM_DIARIO_MARINGA_LONDRINA", "km_diario", "transporte", "", "Maringa/Londrina", "", "", Decimal("80.00"), None, "Media KM diario Maringa/Londrina"),
    ("KM_DIARIO_CAMPO_GRANDE", "km_diario", "transporte", "", "Campo Grande", "", "", Decimal("80.00"), None, "Media KM diario Campo Grande"),
    ("KM_DIARIO_ITAJAI", "km_diario", "transporte", "", "Itajai", "", "", Decimal("80.00"), None, "Media KM diario Itajai"),
    ("KM_DIARIO_PONTA_GROSSA", "km_diario", "transporte", "", "Ponta Grossa", "", "", Decimal("80.00"), None, "Media KM diario Ponta Grossa"),
    ("KM_DIARIO_IRATI", "km_diario", "transporte", "", "Irati", "", "", Decimal("80.00"), None, "Media KM diario Irati"),
    ("KM_DIARIO_PATO_BRANCO", "km_diario", "transporte", "", "Pato Branco", "", "", Decimal("60.00"), None, "Media KM diario Pato Branco"),
    ("KM_DIARIO_DOURADOS", "km_diario", "transporte", "", "Dourados", "", "", Decimal("80.00"), None, "Media KM diario Dourados"),
]


def criar_politicas_oficiais(apps, schema_editor):
    PoliticaValor = apps.get_model("relatorios", "PoliticaValor")
    for chave, tipo_politica, tipo_despesa, tipo_localidade, cidade, origem, destino, limite, valor_km, descricao in POLITICAS_OFICIAIS:
        PoliticaValor.objects.update_or_create(
            chave=chave,
            defaults={
                "tipo_politica": tipo_politica,
                "tipo_despesa": tipo_despesa,
                "tipo_localidade": tipo_localidade,
                "cidade": cidade,
                "origem": origem,
                "destino": destino,
                "limite_valor": limite,
                "valor_km": valor_km,
                "descricao": descricao,
                "vigencia_inicio": date(2026, 1, 1),
                "vigencia_fim": None,
                "ativo": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0035_politicavalor_tipo_localidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicavalor',
            name='chave',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Chave da política'),
        ),
        migrations.AddField(
            model_name='politicavalor',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='politicavalor',
            name='destino',
            field=models.CharField(blank=True, max_length=80, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='politicavalor',
            name='origem',
            field=models.CharField(blank=True, max_length=80, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='politicavalor',
            name='tipo_politica',
            field=models.CharField(choices=[('geral', 'Geral'), ('refeicao', 'Refeição'), ('passagem', 'Passagem'), ('hospedagem', 'Hospedagem'), ('km_diario', 'KM diário / Uber / Táxi'), ('valor_km', 'Valor KM')], default='geral', max_length=20, verbose_name='Tipo da política'),
        ),
        migrations.RunPython(criar_politicas_oficiais, migrations.RunPython.noop),
    ]
