# Generated by Django 6.0.4 on 2026-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0036_politicavalor_chave_politicavalor_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tours_guiados_vistos',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tours guiados vistos'),
        ),
    ]
