# Generated by Django 6.0.4 on 2026-05-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0035_merge_20260525_1501'),
        ('relatorios', '0036_politicavalor_chave_politicavalor_cidade_and_more'),
    ]

    operations = [
    ]
