# Generated by Django 6.0.4 on 2026-05-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0037_merge_20260527_0917'),
        ('relatorios', '0037_perfilusuario_tours_guiados_vistos'),
    ]

    operations = [
    ]
