# Generated by Django 6.0.4 on 2026-05-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0037_perfilusuario_tours_guiados_vistos'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnico',
            name='cidade_atendimento_normalizada',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade normalizada'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='localidade_override',
            field=models.BooleanField(default=False, verbose_name='Localidade alterada manualmente'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='motivo_override_localidade',
            field=models.TextField(blank=True, verbose_name='Motivo da alteração de localidade'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='tipo_localidade_calculada',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('interior', 'Interior'), ('fronteira', 'Fronteira')], max_length=12, verbose_name='Localidade calculada'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='uf_atendimento_normalizada',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF normalizada'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
                ('nome', models.CharField(max_length=120, verbose_name='Município')),
                ('nome_normalizado', models.CharField(db_index=True, max_length=120, verbose_name='Nome normalizado')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], db_index=True, max_length=2, verbose_name='UF')),
                ('uf_nome', models.CharField(max_length=80, verbose_name='Nome da UF')),
                ('eh_capital', models.BooleanField(default=False, verbose_name='É capital')),
                ('tipo_localidade_padrao', models.CharField(choices=[('capital', 'Capital'), ('interior', 'Interior'), ('fronteira', 'Fronteira')], default='interior', max_length=12, verbose_name='Localidade padrão')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='Aliases')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome', 'uf'],
                'indexes': [models.Index(fields=['uf', 'nome_normalizado'], name='relatorios__uf_e78875_idx'), models.Index(fields=['ativo', 'nome_normalizado'], name='relatorios__ativo_2ee059_idx')],
            },
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='municipio_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_atendimento', to='relatorios.municipio', verbose_name='Município de atendimento'),
        ),
    ]
