# Generated by Django 6.0.4 on 2026-05-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0038_merge_20260527_0941'),
        ('relatorios', '0038_relatoriotecnico_cidade_atendimento_normalizada_and_more'),
    ]

    operations = [
    ]
