# Generated by Django 6.0.4 on 2026-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0038_relatoriotecnico_cidade_atendimento_normalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='api_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado na API'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='api_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado na API'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=12, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hash_dados_api',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash dos dados da API'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem_api',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Origem API'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razao social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sincronizado em'),
        ),
    ]
