# Generated by Django 6.0.4 on 2026-05-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0039_cliente_api_created_at_cliente_api_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor_km_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valor KM atualizado em'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_km_atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_valor_km_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Valor KM atualizado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_km_observacao',
            field=models.TextField(blank=True, verbose_name='Observacao do valor KM'),
        ),
    ]
