# Generated by Django 6.0.4 on 2026-05-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0039_merge_20260528_1558'),
        ('relatorios', '0040_cliente_valor_km_atualizado_em_and_more'),
    ]

    operations = [
    ]
