# Generated by Django 6.0.4 on 2026-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0040_cliente_valor_km_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor_km_pendente_api_novo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Valor KM pendente desde importacao API'),
        ),
    ]
