# Generated by Django 6.0.4 on 2026-05-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


SETORES_OFICIAIS = [
    "Administrativo Geral",
    "Comercial e Marketing",
    "Controladoria",
    "Contabilidade",
    "Consultoria Contábil/Societária",
    "Departamento Pessoal",
    "T.I.",
    "T.I. Desenvolvimento",
    "Consultoria Tributária",
    "Jurídico",
    "Jurídico Bancário",
    "Jurídico Tributário",
    "Jurídico Cível e Prazos",
    "Fiscalmax",
]


def criar_setores_oficiais(apps, schema_editor):
    Setor = apps.get_model("relatorios", "Setor")
    for nome in SETORES_OFICIAIS:
        slug_base = slugify(nome)[:130] or "setor"
        slug = slug_base
        contador = 2
        while Setor.objects.filter(slug=slug).exclude(nome=nome).exists():
            slug = f"{slug_base[:125]}-{contador}"
            contador += 1
        Setor.objects.get_or_create(
            nome=nome,
            defaults={"slug": slug, "ativo": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0041_cliente_valor_km_pendente_api_novo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(criar_setores_oficiais, migrations.RunPython.noop),
        migrations.AddField(
            model_name='perfilusuario',
            name='funcao_setor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função/cargo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Setor atualizado em'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor_atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_setor_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Setor atualizado por'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor_confirmado',
            field=models.BooleanField(default=False, verbose_name='Setor confirmado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor_origem',
            field=models.CharField(blank=True, choices=[('importacao', 'Importação'), ('ad', 'AD'), ('usuario', 'Usuário'), ('admin', 'Admin')], max_length=20, verbose_name='Origem do setor'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='funcao_setor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função/cargo'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='setor_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Setor atualizado em'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='setor_atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos_setor_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Setor atualizado por'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='setor_confirmado',
            field=models.BooleanField(default=False, verbose_name='Setor confirmado'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='setor_origem',
            field=models.CharField(blank=True, choices=[('importacao', 'Importação'), ('ad', 'AD'), ('usuario', 'Usuário'), ('admin', 'Admin')], max_length=20, verbose_name='Origem do setor'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='relatorios.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='relatorios.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='UsuarioSetorImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('nome_normalizado', models.CharField(db_index=True, max_length=160, verbose_name='Nome normalizado')),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='Função')),
                ('aplicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aplicado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aplicado', 'Aplicado'), ('ambiguo', 'Ambíguo'), ('inativo', 'Inativo')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_importados', to='relatorios.setor', verbose_name='Setor')),
                ('tecnico_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_importados', to='relatorios.tecnico', verbose_name='Técnico vinculado')),
                ('usuario_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_importados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário vinculado')),
            ],
            options={
                'verbose_name': 'Usuário/setor importado',
                'verbose_name_plural': 'Usuários/setores importados',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome_normalizado', 'ativo'], name='relatorios__nome_no_dd0967_idx'), models.Index(fields=['status', 'ativo'], name='relatorios__status_37d35e_idx')],
            },
        ),
    ]
