# Generated by Django 6.0.4 on 2026-05-31 14:29

import django.db.models.deletion
import relatorios.models
import relatorios.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0042_setor_perfilusuario_funcao_setor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='bi-question-circle', max_length=80, verbose_name='Ícone Bootstrap')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de ajuda',
                'verbose_name_plural': 'Categorias de ajuda',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('formato', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML')], default='html', max_length=20, verbose_name='Formato')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('publico_para', models.JSONField(blank=True, default=list, verbose_name='Público-alvo')),
                ('importante', models.BooleanField(default=False, verbose_name='Importante')),
                ('link_rapido', models.BooleanField(default=False, verbose_name='Link rápido')),
                ('tour_url', models.CharField(blank=True, max_length=255, verbose_name='URL do tour')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_ajuda_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_ajuda_criados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to='relatorios.categoriaajuda', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo de ajuda',
                'verbose_name_plural': 'Artigos de ajuda',
                'ordering': ['categoria__ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ImagemAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=relatorios.storage.HelpImagesStorage(), upload_to=relatorios.models._help_image_upload_to, verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original')),
                ('tipo_mime', models.CharField(blank=True, max_length=120, verbose_name='Tipo MIME')),
                ('tamanho_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamanho')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='relatorios.artigoajuda', verbose_name='Artigo')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_ajuda_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem de ajuda',
                'verbose_name_plural': 'Imagens de ajuda',
                'ordering': ['-criado_em'],
            },
        ),
    ]
