# Generated by Django 6.0.4 on 2026-05-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0041_merge_20260529_1416'),
        ('relatorios', '0042_setor_perfilusuario_funcao_setor_and_more'),
    ]

    operations = [
    ]
