# Generated by Django 6.0.4 on 2026-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0043_categoriaajuda_artigoajuda_imagemajuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoajuda',
            name='artigos_relacionados',
            field=models.ManyToManyField(blank=True, related_name='relacionado_em', symmetrical=False, to='relatorios.artigoajuda', verbose_name='Artigos relacionados'),
        ),
    ]
