# Generated by Django 6.0.4 on 2026-05-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0043_categoriaajuda_artigoajuda_imagemajuda'),
        ('relatorios', '0043_merge_20260529_1633'),
    ]

    operations = [
    ]
