# Generated by Django 6.0.4 on 2026-05-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0044_artigoajuda_artigos_relacionados'),
        ('relatorios', '0044_merge_20260531_1154'),
    ]

    operations = [
    ]
