# Generated by Django 6.0.4 on 2026-06-01 15:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0044_artigoajuda_artigos_relacionados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('legado_planilha', 'Planilha antiga')], db_index=True, default='legado_planilha', max_length=30, verbose_name='Origem')),
                ('is_legado', models.BooleanField(db_index=True, default=True, verbose_name='Legado')),
                ('is_historico_frio', models.BooleanField(db_index=True, default=True, verbose_name='Histórico frio')),
                ('numero_original_legado', models.CharField(db_index=True, max_length=40, verbose_name='Número original')),
                ('arquivo_origem_legado', models.CharField(blank=True, max_length=255, verbose_name='Arquivo de origem')),
                ('linha_origem_legado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Linha de origem')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('observacao_legado', models.TextField(blank=True, verbose_name='Observação legado')),
                ('dados_legado_json', models.JSONField(blank=True, default=dict, verbose_name='Dados brutos do legado')),
                ('escritorio', models.CharField(blank=True, max_length=120, verbose_name='Escritório')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, verbose_name='Cliente legado')),
                ('tecnico_nome', models.CharField(blank=True, max_length=180, verbose_name='Técnico legado')),
                ('tecnico_nome_normalizado', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Técnico normalizado')),
                ('cidade', models.CharField(blank=True, max_length=160, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('tipo_localidade', models.CharField(blank=True, max_length=20, verbose_name='Localidade')),
                ('colaboradores', models.JSONField(blank=True, default=list, verbose_name='Colaboradores')),
                ('diarias', models.JSONField(blank=True, default=list, verbose_name='Diárias')),
                ('periodos', models.JSONField(blank=True, default=list, verbose_name='Períodos')),
                ('data_texto', models.CharField(blank=True, max_length=120, verbose_name='Data/período original')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data fim')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('gasto', models.CharField(blank=True, max_length=80, verbose_name='Gasto')),
                ('reembolso', models.CharField(blank=True, max_length=40, verbose_name='Reembolso')),
                ('valor_adiantamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Adiantamento')),
                ('total_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total despesas')),
                ('total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total KM')),
                ('valor_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor/KM')),
                ('total_km_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total KM valor')),
                ('total_geral', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total geral')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_legados', to='relatorios.cliente', verbose_name='Cliente vinculado')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_legados_importados', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('tecnico_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_legados', to='relatorios.tecnico', verbose_name='Técnico vinculado')),
            ],
            options={
                'verbose_name': 'Relatório legado',
                'verbose_name_plural': 'Relatórios legados',
                'ordering': ['-data_inicio', '-numero_original_legado'],
            },
        ),
        migrations.CreateModel(
            name='KmLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='KM')),
                ('valor_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor/KM')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total')),
                ('dados_legado_json', models.JSONField(blank=True, default=dict, verbose_name='Dados brutos')),
                ('relatorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='km_legado', to='relatorios.relatoriolegado', verbose_name='Relatório legado')),
            ],
            options={
                'verbose_name': 'KM legado',
                'verbose_name_plural': 'KMs legados',
            },
        ),
        migrations.CreateModel(
            name='DespesaLegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('data_original', models.CharField(blank=True, max_length=80, verbose_name='Data original')),
                ('documento', models.CharField(blank=True, max_length=120, verbose_name='Documento')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('tipo_codigo', models.CharField(blank=True, max_length=20, verbose_name='Tipo código')),
                ('tipo_descricao', models.CharField(blank=True, max_length=80, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor')),
                ('dados_legado_json', models.JSONField(blank=True, default=dict, verbose_name='Dados brutos')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='relatorios.relatoriolegado', verbose_name='Relatório legado')),
            ],
            options={
                'verbose_name': 'Despesa legada',
                'verbose_name_plural': 'Despesas legadas',
                'ordering': ['relatorio', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='relatoriolegado',
            index=models.Index(fields=['origem', 'numero_original_legado'], name='relatorios__origem_1b8159_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriolegado',
            index=models.Index(fields=['data_inicio'], name='relatorios__data_in_3e23d0_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriolegado',
            index=models.Index(fields=['cliente_nome'], name='relatorios__cliente_ae20e6_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriolegado',
            index=models.Index(fields=['tecnico_nome_normalizado'], name='relatorios__tecnico_16d089_idx'),
        ),
        migrations.AddConstraint(
            model_name='relatoriolegado',
            constraint=models.UniqueConstraint(fields=('origem', 'numero_original_legado'), name='uniq_relatorio_legado_origem_numero'),
        ),
        migrations.AddIndex(
            model_name='despesalegada',
            index=models.Index(fields=['relatorio', 'ordem'], name='relatorios__relator_33fed5_idx'),
        ),
    ]
