# Generated by Django 6.0.4 on 2026-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0045_relatoriolegado_kmlegado_despesalegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='ad_distinguished_name',
            field=models.TextField(blank=True, verbose_name='DN no AD'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ad_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado com AD em'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ad_user_principal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Principal Name'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ad_username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='Usuário AD'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='origem_ad',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Origem AD'),
        ),
    ]
