# Generated by Django 6.0.4 on 2026-06-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0045_merge_20260531_1534'),
        ('relatorios', '0045_relatoriolegado_kmlegado_despesalegada_and_more'),
    ]

    operations = [
    ]
