# Generated by Django 6.0.4 on 2026-06-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0046_merge_20260601_1253'),
        ('relatorios', '0046_tecnico_ad_distinguished_name_and_more'),
    ]

    operations = [
    ]
