# Generated by Django 6.0.4 on 2026-06-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0046_tecnico_ad_distinguished_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdespesa',
            name='tipo',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('passagem', 'Passagem'), ('transporte', 'Transporte'), ('estacionamento', 'Estacionamento'), ('material', 'Material / Ferramentas'), ('comunicacao', 'Comunicação / Telefone'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='politicavalor',
            name='tipo_despesa',
            field=models.CharField(blank=True, choices=[('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('passagem', 'Passagem'), ('transporte', 'Transporte'), ('estacionamento', 'Estacionamento'), ('material', 'Material / Ferramentas'), ('comunicacao', 'Comunicação / Telefone'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de despesa'),
        ),
    ]
