# Generated by Django 6.0.4 on 2026-06-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0047_alter_itemdespesa_tipo_and_more'),
        ('relatorios', '0047_merge_20260602_0931'),
    ]

    operations = [
    ]
