# Generated by Django 6.0.4 on 2026-06-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0047_alter_itemdespesa_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnico',
            name='tipo_reembolso',
            field=models.CharField(choices=[('reembolsavel', 'Reembolsável'), ('nao_reembolsavel', 'Não reembolsável')], default='reembolsavel', max_length=20, verbose_name='Tipo de reembolso'),
        ),
    ]
