# Generated by Django 6.0.4 on 2026-06-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0048_merge_20260603_0835'),
        ('relatorios', '0048_relatoriotecnico_tipo_reembolso'),
    ]

    operations = [
    ]
