# Generated by Django 6.0.4 on 2026-06-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0048_relatoriotecnico_tipo_reembolso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=80, verbose_name='Tipo')),
                ('destinatarios', models.JSONField(blank=True, default=list, verbose_name='Destinatários')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('corpo', models.TextField(blank=True, verbose_name='Corpo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falha', 'Falha')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_log', to='relatorios.relatoriotecnico')),
            ],
            options={
                'verbose_name': 'Log de e-mail',
                'verbose_name_plural': 'Logs de e-mail',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'tipo'], name='relatorios__status_299330_idx'), models.Index(fields=['relatorio', 'tipo'], name='relatorios__relator_20e2f0_idx')],
            },
        ),
    ]
