# Generated by Django 6.0.4 on 2026-06-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0049_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriotecnico',
            name='tipo_relatorio',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('institucional', 'Institucional'), ('operacional', 'Operacional'), ('treinamento', 'Treinamento')], default='operacional', max_length=20, verbose_name='Tipo de relatorio'),
        ),
    ]
