# Generated by Django 6.0.4 on 2026-06-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0049_emaillog'),
        ('relatorios', '0049_merge_20260603_0842'),
    ]

    operations = [
    ]
