# Generated by Django 6.0.4 on 2026-06-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0050_alter_relatoriotecnico_tipo_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnico',
            name='empresa_grupo',
            field=models.CharField(blank=True, choices=[('blazius_e_lorenzetti', 'BLAZIUS E LORENZETTI'), ('controlsul', 'CONTROLSUL'), ('fiscalmax', 'FISCALMAX')], max_length=30, verbose_name='Empresa responsável pelo custo'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='tecnico_reembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_reembolso', to='relatorios.tecnico', verbose_name='Técnico reembolsado'),
        ),
    ]
