# Generated by Django 6.0.4 on 2026-06-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0051_relatoriotecnico_empresa_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='reenviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_reenviados', to=settings.AUTH_USER_MODEL, verbose_name='Reenviado por'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='ultimo_reenvio_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último reenvio em'),
        ),
    ]
