# Generated by Django 6.0.4 on 2026-06-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0050_merge_0049_emaillog_0049_merge_20260603_0842'),
        ('relatorios', '0052_emaillog_reenviado_por_emaillog_ultimo_reenvio_em'),
    ]

    operations = [
    ]
