# Generated by Django 6.0.4 on 2026-07-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0053_merge_20260615_1023'),
        ('relatorios', '0053_relatorioautosave'),
    ]

    operations = [
    ]
