# Generated by Django 6.0.4 on 2026-07-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0054_merge_0053_merge_20260615_1023_0053_relatorioautosave'),
        ('relatorios', '0056_cidadeatendimento'),
    ]

    operations = [
    ]
