# Generated by Django 6.0.4 on 2026-08-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0057_alter_historicorelatorio_tipo_evento_reaberto'),
        ('relatorios', '0057_merge_20260713_1650'),
    ]

    operations = [
    ]
